---
ci:
    autoupdate_schedule: quarterly

repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: check-json
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
    - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
    - id: flake8
      args: [--count, --show-source, --statistics]
      additional_dependencies: [flake8-bugbear]

  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.5.0
    hooks:
    - id: setup-cfg-fmt

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
